local H = ...

H.test("isFinite rejects NaN, infinities and non-numbers", function()
    local ns = H.newNS("Util")
    H.truthy(ns.Util.isFinite(0))
    H.truthy(ns.Util.isFinite(-5.5))
    H.falsy(ns.Util.isFinite(0 / 0))
    H.falsy(ns.Util.isFinite(1 / 0))
    H.falsy(ns.Util.isFinite(-1 / 0))
    H.falsy(ns.Util.isFinite("1"))
    H.falsy(ns.Util.isFinite(nil))
    H.falsy(ns.Util.isFinite({}))
end)

H.test("isCopper accepts zero and positives only", function()
    local ns = H.newNS("Util")
    H.truthy(ns.Util.isCopper(0))
    H.truthy(ns.Util.isCopper(12345))
    H.falsy(ns.Util.isCopper(-1))
    H.falsy(ns.Util.isCopper(0 / 0))
    H.falsy(ns.Util.isCopper(1 / 0))
    H.falsy(ns.Util.isCopper(nil))
end)

H.test("count floors and rejects below one", function()
    local ns = H.newNS("Util")
    H.eq(ns.Util.count(3), 3)
    H.eq(ns.Util.count(2.9), 2)
    H.eq(ns.Util.count(0), nil)
    H.eq(ns.Util.count(0.5), nil)
    H.eq(ns.Util.count(-4), nil)
    H.eq(ns.Util.count(0 / 0), nil)
    H.eq(ns.Util.count(1 / 0), nil)
    H.eq(ns.Util.count("3"), nil)
end)

H.test("id accepts only exact positive integers", function()
    local ns = H.newNS("Util")
    H.eq(ns.Util.id(7), 7)
    H.eq(ns.Util.id(7.5), nil)
    H.eq(ns.Util.id(0), nil)
    H.eq(ns.Util.id(-1), nil)
    H.eq(ns.Util.id(0 / 0), nil)
    H.eq(ns.Util.id(nil), nil)
end)

H.test("clamp bounds a value", function()
    local ns = H.newNS("Util")
    H.eq(ns.Util.clamp(5, 0, 10), 5)
    H.eq(ns.Util.clamp(-5, 0, 10), 0)
    H.eq(ns.Util.clamp(50, 0, 10), 10)
end)

H.test("round goes half away from zero", function()
    local ns = H.newNS("Util")
    H.eq(ns.Util.round(2.4), 2)
    H.eq(ns.Util.round(2.5), 3)
    H.eq(ns.Util.round(-2.4), -2)
    H.eq(ns.Util.round(-2.5), -3)
    H.eq(ns.Util.round(0), 0)
end)
